name: altive_chat_room
description: |
  altive_chat_room provides the UI used for chatting.
  One-to-one chats like DM and group chats are possible.
  Text and image messages can also be sent.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  cached_network_image: ^3.4.1
  cached_network_svg_image: ^2.0.0
  clock: ^1.1.2
  collection: ^1.19.1
  custom_refresh_indicator: ^4.0.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_linkify: ^6.0.0
  flutter_svg: ^2.2.3
  html: ^0.15.6
  http: ^1.6.0
  intl: ^0.20.2
  linkify: ^5.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  altive_lints: ^2.1.0
  flutter_test:
    sdk: flutter
